### ISSUE TITLE
Nudges

### ISSUE THREAD

**Issue by ariG23498** [Chandril98/FirstAttempt#2]
# Back Button
![lol](https://user-images.githubusercontent.com/36856589/56845245-f770c480-68db-11e9-86c1-60ceaed64a0e.png)
In the above screenshot there is no back button to return to the home page. Give it a thought as soon as possible.
# Link
The alert message has a git hub profile link, think of a better way to portray the link, so that the user can actually land to your github profile.
![9 year old](https://user-images.githubusercontent.com/36856589/56845261-3141cb00-68dc-11e9-8d58-6d14e184d988.png)

**Comment by Chandril98** [comment]
Back button issue solved .. please check for further upgrade or issue

**Comment by ariG23498** [comment]
Closing the issue, will watch the repo for further upgrades.
